### ISSUE TITLE
Please credit Renee French

### ISSUE THREAD

**Issue by nf** [hackraft/gophericons#1]
Most of the gopher images you include are based directly on the gopher design by Renee French, which is Creative Commons 3.0 Attributions licensed. You must give her attribution when you distribute these works. Thanks.

https://blog.golang.org/gopher

**Comment by shalakhin** [comment]
Ok. I will add it in a few hours.

Thank you!

**Comment by shalakhin** [comment]
@nf is it right now correct? It would be great if you add it to Golang site so people can find it and use it.

P.S. svg added too.

**Comment by nathany** [comment]
@shalakhin I've linked these icons from the wiki https://github.com/golang/go/wiki/Gopher. Thanks to Olga and yourself for providing the community with them!

**Comment by nathany** [comment]
- You may want to be more clear as to the license Olga is putting these new illustrations under, whether Creative Commons Attribution or wtfpl as before. 
- You may also want to put Olga's license first followed by the "based on/derived from" part with Renee French (at least that's what I do for my gopher photos).
- Finally, you may want to also link to the actual license, eg.: http://creativecommons.org/licenses/by/3.0/

You can click through to the [wiki](https://github.com/golang/go/wiki/Gopher) to see what others have done for illustrations.

Thanks.

**Comment by shalakhin** [comment]
@nf updated. Thank you again for help with licensing! We plan to also add cyber gophers

**Comment by shalakhin** [comment]
@nf now it is OK?

**Comment by shalakhin** [comment]
Seems it is ok now. Close the issue.
