### ISSUE TITLE
SVG versions

### ISSUE THREAD

**Issue by brandonb927** [hackraft/gophericons#2]
The `ai` files are awesome if you have Illustrator installed, but it'd be neat to get SVG versions of these images too :)

**Comment by shalakhin** [comment]
We will add it today. Thank you!

**Comment by nathany** [comment]
Thanks. SVG exports would be great.

**Comment by shalakhin** [comment]
@nathany  svg images added

**Comment by brandonb927** [comment]
Fantastic! Thanks @shalakhin
